zookeeper:
  config:
    clientPort: 2181
broker:
  config:
# This should be 9092 for plaintext, 9093 for ssl. Just hardcoding to 9093 as we're just using ssl.
    port: 9093
confluent:
  package_name: confluent-platform-2.11
  support:
    customer_id: anonymous
# turn off metrics for now.
    metrics_enabled: false
  repository:
    debian:
# We want to access these packages through a local mirror, using aptly.
      key_url: http://aptly.jupiter.bbc.co.uk/aptly/key.pub.txt
      repository: "deb [arch=amd64] http://aptly.jupiter.bbc.co.uk/aptly/confluent-5.2/ stable main"
    redhat:
      main:
        baseurl: https://packages.confluent.io/rpm/5.1
        gpgcheck: 1
        gpgkey: https://packages.confluent.io/rpm/5.1/archive.key
        enabled: 1
      dist:
        baseurl: https://packages.confluent.io/rpm/5.1/7
        gpgcheck: 1
        gpgkey:  https://packages.confluent.io/rpm/5.1/archive.key
        enabled: 1
