# Don't see the need for this - openjdk-8-jdk installs fine from standard ubuntu repositories and is a later version.
#- name: Add open JDK repo
#  apt_repository:
#    repo: ppa:openjdk-r/ppa
- name: Install Java
  apt:
    name: "openjdk-8-jdk"
    update_cache: yes
- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'
